### ISSUE TITLE
Libflac decoder crash: flac_jni.cc (NewStringUTF)

### ISSUE THREAD

**Issue by sx1101** [androidx/media#1558]
### Version

Media3 1.3.1

### Devices that reproduce the issue

Xiaomi 12
Realme C35

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Play the attached file using libflac (https://github.com/androidx/media/tree/release/libraries/decoder_flac)
2. Crash

### Expected result

No crash

### Actual result

App crashes with the following stack trace:
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/cupid_eea/cupid:13/TKQ1.220807.001/V14.0.15.0.TLCEUXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2024-07-17 11:05:26.018397541+0300
Process uptime: 36s
ZygotePid: 798492623
Cmdline: com.zvooq.openplay
pid: 5087, tid: 5889, name: ExoPlayer:Loade  >>> com.zvooq.openplay <<<
uid: 10498
tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0xe5
    string: 'title=???? ???????? ? ??????? ???????? - ??????'
    input: '0x74 0x69 0x74 0x6c 0x65 0x3d 0xc6 <0xe5> 0xed 0xff 0x20 0xd2 0xf0 0xee 0xf4 0xe8 0xec 0xee 0xe2 0x20 0xe8 0x20 0xca 0xee 0xec 0xed 0xe0 0xf2 0xe0 0x20 0xea 0xf3 0xeb 0xfc 0xf2 0xf3 0xf0 0xfb 0x20 0x2d 0x20 0xcf 0xee 0xe5 0xe7 0xe4 0xe0'
    in call to NewStringUTF
    from androidx.media3.extractor.FlacStreamMetadata androidx.media3.decoder.flac.FlacDecoderJni.flacDecodeMetadata(long)'
    x0  0000000000000000  x1  0000000000001701  x2  0000000000000006  x3  0000007431f0f100
    x4  fefefefefefefeff  x5  fefefefefefefeff  x6  fefefefefefefeff  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  00000076722eac70  x10 0000000000000001  x11 000000767235f608
    x12 00000073c81e7030  x13 0000000016775f50  x14 0000000016775e10  x15 ffffffffffffffff
    x16 00000076723caa68  x17 00000076723a3290  x18 00000073aa41e000  x19 00000000000013df
    x20 0000000000001701  x21 00000000ffffffff  x22 0000000000000058  x23 00000075c7aa3b86
    x24 0000000000000058  x25 0000000000000001  x26 0000000000000000  x27 00000075c8616000
    x28 b4000076787211c0  x29 0000007431f0f180
    lr  0000007672350588  sp  0000007431f0f0e0  pc  00000076723505b4  pst 0000000000001000
backtrace:
      #00 pc 000000000008d5b4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 607a29162b319a50c57abd2b2141d335)
      #01 pc 000000000076fba0  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+904) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #02 pc 00000000000357d0  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80) (BuildId: 6f67f69ff36b970d0b831cfdab3b578d)
      #03 pc 0000000000034d58  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+352) (BuildId: 6f67f69ff36b970d0b831cfdab3b578d)
      #04 pc 00000000003eaa4c  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+3540) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #05 pc 00000000002cd354  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::AbortF(char const*, ...) (.__uniq.99033978352804627313491551960229047428)+188) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #06 pc 0000000000385ac8  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const*, art::(anonymous namespace)::JniValueType*) (.__uniq.99033978352804627313491551960229047428)+3532) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #07 pc 000000000054cee4  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::CheckJNI::NewStringUTF(_JNIEnv*, char const*) (.__uniq.99033978352804627313491551960229047428.llvm.11330922511402509615)+160) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #08 pc 000000000002f5ec  /data/app/~~7I8Cqqc3rZRFVKBFRB5UOw==/com.zvooq.openplay-jRjeuJSuazgrDhsKqUhgMg==/lib/arm64/libflacJNI.so (Java_androidx_media3_decoder_flac_FlacDecoderJni_flacDecodeMetadata+420) (BuildId: cef79c4e94d4dc8a443c97a2e825eaba55fca42d)
      #09 pc 0000000000351230  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+144) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #10 pc 000000000033a7a4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #11 pc 0000000000510988  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+1976) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #12 pc 00000000004908c8  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+2092) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #13 pc 00000000003539d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #14 pc 0000000000178050  [anon:dalvik-classes2.dex extracted in memory from /data/app/~~7I8Cqqc3rZRFVKBFRB5UOw==/com.zvooq.openplay-jRjeuJSuazgrDhsKqUhgMg==/base.apk!classes2.dex] (androidx.media3.decoder.flac.FlacDecoderJni.decodeStreamMetadata+0)
      #15 pc 000000000036daec  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.18012138979834229341)+232) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #16 pc 0000000000511654  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+5252) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #17 pc 0000000000490490  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+1012) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #18 pc 00000000003539d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #19 pc 0000000000178b5c  [anon:dalvik-classes2.dex extracted in memory from /data/app/~~7I8Cqqc3rZRFVKBFRB5UOw==/com.zvooq.openplay-jRjeuJSuazgrDhsKqUhgMg==/base.apk!classes2.dex] (androidx.media3.decoder.flac.FlacExtractor.decodeStreamMetadata+0)
      #20 pc 000000000036daec  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.18012138979834229341)+232) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #21 pc 0000000000511654  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+5252) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #22 pc 00000000004908c8  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+2092) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #23 pc 00000000003539d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #24 pc 0000000000178988  [anon:dalvik-classes2.dex extracted in memory from /data/app/~~7I8Cqqc3rZRFVKBFRB5UOw==/com.zvooq.openplay-jRjeuJSuazgrDhsKqUhgMg==/base.apk!classes2.dex] (androidx.media3.decoder.flac.FlacExtractor.read+0)
      #25 pc 000000000036daec  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.18012138979834229341)+232) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #26 pc 0000000000511654  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+5252) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #27 pc 0000000000491340  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+4772) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #28 pc 00000000003539d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #29 pc 000000000047c33c  [anon:dalvik-classes21.dex extracted in memory from /data/app/~~7I8Cqqc3rZRFVKBFRB5UOw==/com.zvooq.openplay-jRjeuJSuazgrDhsKqUhgMg==/base.apk!classes21.dex] (androidx.media3.exoplayer.source.BundledExtractorsAdapter.read+0)
      #30 pc 000000000036daec  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.18012138979834229341)+232) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #31 pc 0000000000511654  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+5252) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #32 pc 0000000000491340  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+4772) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #33 pc 00000000003539d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #34 pc 00000000004861a4  [anon:dalvik-classes21.dex extracted in memory from /data/app/~~7I8Cqqc3rZRFVKBFRB5UOw==/com.zvooq.openplay-jRjeuJSuazgrDhsKqUhgMg==/base.apk!classes21.dex] (androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load+0)
      #35 pc 000000000036daec  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.18012138979834229341)+232) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #36 pc 0000000000511654  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+5252) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #37 pc 0000000000491340  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+4772) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #38 pc 00000000003539d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #39 pc 00000000004a53e0  [anon:dalvik-classes21.dex extracted in memory from /data/app/~~7I8Cqqc3rZRFVKBFRB5UOw==/com.zvooq.openplay-jRjeuJSuazgrDhsKqUhgMg==/base.apk!classes21.dex] (androidx.media3.exoplayer.upstream.Loader$LoadTask.run+0)
      #40 pc 000000000036daec  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.18012138979834229341)+232) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #41 pc 000000000036d3e4  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+964) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #42 pc 0000000000351368  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 5b1e3dce5abfbdc410d71d256d308227)
      #43 pc 0000000002012480  /memfd:jit-cache (deleted)
```
- - -
jstring commentString = env->NewStringUTF((*vorbisComment).c_str());

`
Data passed to NewStringUTF must be in Modified UTF-8 format. A common mistake is reading character data from a file or network stream and handing it to NewStringUTF without filtering it. Unless you know the data is valid MUTF-8 (or 7-bit ASCII, which is a compatible subset), you need to strip out invalid characters or convert them to proper Modified UTF-8 form
`

https://developer.android.com/training/articles/perf-jni#utf-8-and-utf-16-strings

### Media

[problem_file_cut.flac.zip](https://github.com/user-attachments/files/16314830/problem_file_cut.flac.zip)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.
